spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/containeros?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456

#logging:
#  level:
#    root: info
#    me.autubrew.website: debug
#  file:
#    name: log/blog-dev.log
