server:
  port: 80
spring:
  thymeleaf:
    prefix: classpath:/static/
    cache : false
    mode : LEGACYHTML5
    suffix : .html
  datasource:
    username: website
    password: 123456
    url: jdbc:mysql://47.240.43.166:3306/docker?characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/Mapper/*.xml
  type-aliases-package: com.hust.docker.entity